spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test-demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
  redis:
    host: 39.106.217.31
#    host: 127.0.0.1
    port: 6379
#    password:
    password: chendada
    database: 3
    timeout: 30000ms
server:
  port: 1122
